polc/accounts/urls.py
from django.conf.urls import url
from django.conf.urls import include
from django.contrib import admin
from django.views.generic.base import RedirectView
from django.conf import settings
from django.conf.urls.static import static

from .views import settings, password, signup
# from .views import activate, account_activation_sent


from .views import (
    UserDetailView
)





urlpatterns = [
      url(r'^settings/$', settings, name='settings'),
      url(r'^settings/password/$', password, name='password'),
      url(r'^signup/$', signup, name='signup'),
      url(r'^(?P<username>[\w.@+-]+)/$', UserDetailView.as_view(), name='profile'), 
      # url(r'^account_activation_sent/$', account_activation_sent, name='account_activation_sent'),
      # url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
      #  activate, name='activate'),
]

polc/candidateapp/urls.py
from django.conf.urls import url
from django.conf.urls import include
from django.contrib import admin
from django.views.generic.base import RedirectView
from django.conf import settings
from django.conf.urls.static import static

from .views import (
    CandidateListView,
    CandidateDetailView
)


urlpatterns = [
      url(r'^$', RedirectView.as_view(url='/')), 
      url(r'^search/$', CandidateListView.as_view(), name='candidatelist'), 
      # url(r'^(?P<pk>\d+)/$', PolitDetailView.as_view(), name='politdetail'), 
      url(r'^(?P<slug>[\w-]+)/$',CandidateDetailView.as_view(), name='candidatedetail'),
]

polc/polc/urls.py
# from django.conf.urls import url
# from django.contrib import admin

# urlpatterns = [
#     url(r'^admin/', admin.site.urls),
# ]

from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views

from django.conf import settings
from django.conf.urls.static import static
from .views import home, settings, password
from django.conf.urls import url, include
from django.contrib import admin




urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^candidates/', include('candidateapp.urls', namespace='candidatesapp')),
    url(r'^$', home, name = 'home'),
    url(r'^oauth/', include('social_django.urls', namespace='social')),  
    url(r'^login/$', auth_views.login, name='login'),
    url(r'^logout/$', auth_views.logout, name='logout'),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^api/candidates/', include('candidateapp.api.urls', namespace='candiateapp-api')),
    url(r'^api/graph/', include('visualisation.api.urls', namespace='graph-api')),
]

polc/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Landing Page - Start Bootstrap Theme</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom fonts for this template -->
    <link href="{% static 'vendor/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'vendor/simple-line-icons/css/simple-line-icons.css' %}" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Lato|Libre+Baskerville" rel="stylesheet">

    <link href="{% static 'octicons/build/font/octicons.css' %}" rel="stylesheet">
    <link href="{% static 'icons/css/ionicons.css' %}" rel="stylesheet">
    <link href="{% static 'icons/css/ionicons.min.css' %}" rel="stylesheet">
    <!-- Custom styles for this template -->
    <link href="{% static 'css/landing-page.min.css' %}"  rel="stylesheet">
    <link href="{% static 'static/custom.css' %}"  rel="stylesheet">
    <link href="{% static 'lib/jquery.upvote.css' %}"  rel="stylesheet">
  </head>

  <body>

    <div class='container col-sm-12'>
                {% include "navbar.html" %}
            {% block content %}           
                Home page 
            {% endblock content %}

    </div>

    <!-- Bootstrap core JavaScript -->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="{% static 'js/search.js' %}"></script>
    <script src="{% static 'lib/jquery.upvote.js' %}"></script>
    
    <script src="http://d3js.org/d3.v3.js"></script>
    <script src="{% static 'js/visualisation.js' %}"></script>
    {% block script %}{% endblock script %}


  </body>
  <footer>
          <div class='container-fluid  pt-5 mt-5'>
            <hr/>
               {% include "footer.html" %}
      </div>
  </footer>



 
</html>

polc/templates/footer.html
<div class="card text-center">
  <div class="card-header">
    Featured
  </div>
  <div class="card-body">
    <h5 class="card-title">Special title treatment</h5>
    <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
    <a href="#" class="btn btn-primary">Go somewhere</a>
  </div>
  <div class="card-footer text-muted">
    2 days ago
  </div>
</div>

polc/templates/home.html
{% extends "base.html" %}
{% load static %}
{% block title %}{{ block.super }} | Welcome{% endblock title %}

<!-- {% block script %} -->

<script src="{% static 'js/custom.js' %}"></script>

<!-- {% endblock script %} -->


{% block content %}

    <!-- Masthead -->
    <header class="masthead text-white text-center">
      <div class="overlay"></div>
      <div class="container">
        <div class="row">
          <div class="col-xl-9 mx-auto">
            <h1 class="mb-5 lead"> Let the politicians hear your voice!</h1>
          </div>
          <div class="col-md-10 col-lg-8 col-xl-7 mx-auto">
            {% include "search_form.html" %}
          </div>
        </div>
      </div>
    </header>

<div class="container">

      <h1 class="my-4 font-weight-bold"> Politicians <small class ="text-muted h6 font-italic text-capitalize blockqoute-footer"> Currently in Parliment </small></h1>

      <!-- Marketing Icons Section -->
      <div class="row">
        <div class="col-lg-4 mb-4">
          <div class="card h-100">
            <h4 class="card-header">Card Title</h4>
            <div class="card-body">
              <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sapiente esse necessitatibus neque.</p>
            </div>
            <div class="card-footer">
              <a href="#" class="btn btn-primary">Learn More</a>
            </div>
          </div>
        </div>
        <div class="col-lg-4 mb-4">
          <div class="card h-100">
            <h4 class="card-header">Card Title</h4>
            <div class="card-body">
              <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Reiciendis ipsam eos, nam perspiciatis natus commodi similique totam consectetur praesentium molestiae atque exercitationem ut consequuntur, sed eveniet, magni nostrum sint fuga.</p>
            </div>
            <div class="card-footer">
              <a href="#" class="btn btn-primary">Learn More</a>
            </div>
          </div>
        </div>
        <div class="col-lg-4 mb-4">
          <div class="card h-100">
            <h4 class="card-header">Card Title</h4>
            <div class="card-body">
              <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sapiente esse necessitatibus neque.</p>
            </div>
            <div class="card-footer">
              <a href="#" class="btn btn-primary">Learn More</a>
            </div>
          </div>
        </div>
      </div>
      <!-- /.row -->

       </br>
      <!-- Portfolio Section -->
      <h2>Biggest Gainers and Losers </h2>


          {% if user.is_authenticated %}
                     <p class="display-4">Hello, {{ user.username }}</p>
          {% else %}
                     <a class="lead" href="{% url 'login' %}">Log in</a>
          {% endif %}


   <hr/>
       </br>
      <h3>Gaining popularity! </h3>
      <div class="row">
        <div class="col-lg-4 col-sm-6 portfolio-item">
          <div class="card h-100">
            <a href="#"><img class="card-img-top" src="http://placehold.it/700x400" alt=""></a>
            <div class="card-body">
              <h4 class="card-title">
                <a href="#">Project One</a>
              </h4>
              <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet numquam aspernatur eum quasi sapiente nesciunt? Voluptatibus sit, repellat sequi itaque deserunt, dolores in, nesciunt, illum tempora ex quae? Nihil, dolorem!</p>
            </div>
          </div>
        </div>
        <div class="col-lg-4 col-sm-6 portfolio-item">
          <div class="card h-100">
            <a href="#"><img class="card-img-top" src="http://placehold.it/700x400" alt=""></a>
            <div class="card-body">
              <h4 class="card-title">
                <a href="#">Project Two</a>
              </h4>
              <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam viverra euismod odio, gravida pellentesque urna varius vitae.</p>
            </div>
          </div>
        </div>
        <div class="col-lg-4 col-sm-6 portfolio-item">
          <div class="card h-100">
            <a href="#"><img class="card-img-top" src="http://placehold.it/700x400" alt=""></a>
            <div class="card-body">
              <h4 class="card-title">
                <a href="#">Project Three</a>
              </h4>
              <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quos quisquam, error quod sed cumque, odio distinctio velit nostrum temporibus necessitatibus et facere atque iure perspiciatis mollitia recusandae vero vel quam!</p>
            </div>
          </div>
        </div>
        <div class="col-lg-4 col-sm-6 portfolio-item">
          <div class="card h-100">
            <a href="#"><img class="card-img-top" src="http://placehold.it/700x400" alt=""></a>
            <div class="card-body">
              <h4 class="card-title">
                <a href="#">Project Four</a>
              </h4>
              <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam viverra euismod odio, gravida pellentesque urna varius vitae.</p>
            </div>
          </div>
        </div>
        <div class="col-lg-4 col-sm-6 portfolio-item">
          <div class="card h-100">
            <a href="#"><img class="card-img-top" src="http://placehold.it/700x400" alt=""></a>
            <div class="card-body">
              <h4 class="card-title">
                <a href="#">Project Five</a>
              </h4>
              <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam viverra euismod odio, gravida pellentesque urna varius vitae.</p>
            </div>
          </div>
        </div>
        <div class="col-lg-4 col-sm-6 portfolio-item">
          <div class="card h-100">
            <a href="#"><img class="card-img-top" src="http://placehold.it/700x400" alt=""></a>
            <div class="card-body">
              <h4 class="card-title">
                <a href="#">Project Six</a>
              </h4>
              <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Itaque earum nostrum suscipit ducimus nihil provident, perferendis rem illo, voluptate atque, sit eius in voluptates, nemo repellat fugiat excepturi! Nemo, esse.</p>
            </div>
          </div>
        </div>
      </div>
      <!-- /.row -->
    </br>
   <hr/>
   <h3> Loosing popularity  </h3>

      <div class="row">
        <div class="col-lg-4 col-sm-6 portfolio-item">
          <div class="card h-100">
            <a href="#"><img class="card-img-top" src="http://placehold.it/700x400" alt=""></a>
            <div class="card-body">
              <h4 class="card-title">
                <a href="#">Project One</a>
              </h4>
              <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet numquam aspernatur eum quasi sapiente nesciunt? Voluptatibus sit, repellat sequi itaque deserunt, dolores in, nesciunt, illum tempora ex quae? Nihil, dolorem!</p>
            </div>
          </div>
        </div>
        <div class="col-lg-4 col-sm-6 portfolio-item">
          <div class="card h-100">
            <a href="#"><img class="card-img-top" src="http://placehold.it/700x400" alt=""></a>
            <div class="card-body">
              <h4 class="card-title">
                <a href="#">Project Two</a>
              </h4>
              <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam viverra euismod odio, gravida pellentesque urna varius vitae.</p>
            </div>
          </div>
        </div>
        <div class="col-lg-4 col-sm-6 portfolio-item">
          <div class="card h-100">
            <a href="#"><img class="card-img-top" src="http://placehold.it/700x400" alt=""></a>
            <div class="card-body">
              <h4 class="card-title">
                <a href="#">Project Three</a>
              </h4>
              <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quos quisquam, error quod sed cumque, odio distinctio velit nostrum temporibus necessitatibus et facere atque iure perspiciatis mollitia recusandae vero vel quam!</p>
            </div>
          </div>
        </div>
        <div class="col-lg-4 col-sm-6 portfolio-item">
          <div class="card h-100">
            <a href="#"><img class="card-img-top" src="http://placehold.it/700x400" alt=""></a>
            <div class="card-body">
              <h4 class="card-title">
                <a href="#">Project Four</a>
              </h4>
              <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam viverra euismod odio, gravida pellentesque urna varius vitae.</p>
            </div>
          </div>
        </div>
        <div class="col-lg-4 col-sm-6 portfolio-item">
          <div class="card h-100">
            <a href="#"><img class="card-img-top" src="http://placehold.it/700x400" alt=""></a>
            <div class="card-body">
              <h4 class="card-title">
                <a href="#">Project Five</a>
              </h4>
              <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam viverra euismod odio, gravida pellentesque urna varius vitae.</p>
            </div>
          </div>
        </div>
        <div class="col-lg-4 col-sm-6 portfolio-item">
          <div class="card h-100">
            <a href="#"><img class="card-img-top" src="http://placehold.it/700x400" alt=""></a>
            <div class="card-body">
              <h4 class="card-title">
                <a href="#">Project Six</a>
              </h4>
              <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Itaque earum nostrum suscipit ducimus nihil provident, perferendis rem illo, voluptate atque, sit eius in voluptates, nemo repellat fugiat excepturi! Nemo, esse.</p>
            </div>
          </div>
        </div>
      </div>
      <!-- /.row -->
    <!-- /.container -->
{% endblock content %}

polc/templates/navbar.html
<nav class="navbar  navbar-expand-lg navbar-dark bg-dark pb-1" >
  <div class='container'>
        <a class="navbar-brand" href="{% url 'home' %}">
            <!-- <img src="/assets/brand/bootstrap-solid.svg" width="30" height="30" alt=""> -->
            <a class="navbar-brand" href="{% url 'home' %}">Politico </a>
             <!-- <a class="btn btn-primary pull-right" href="#">Sign In</a> -->
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
         <div class='container'>
            <form class="form-inline my-1 my-lg-1m float-right  ">
                <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
            </form>
        </div>
 
    </div>
    
    {% if user.username  %}
      <ul class="nav nav-pills">
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Hello, {{ user.username }}</a>
            <div class="dropdown-menu">
              <a class="dropdown-item" href="{% url 'accounts:settings' %}">Settings</a>
              <a class="dropdown-item" href="{% url 'accounts:settings' %}">About</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="{% url 'logout' %}">Logout</a>
            </div>
          </li>
      </ul>
    {% else %}
      <a href="{% url 'accounts:settings' %}">Login </a>
    {% endif %}
</nav>


<!-- 
    <nav class="navbar navbar-light bg-light static-top">
      <div class="container">
        <a class="navbar-brand" href="#">Politico </a>
        <a class="btn btn-primary" href="#">Sign In</a>
      </div>
    </nav> -->

polc/templates/search.html
{% extends "base.html" %}

<style>
#tweet-container {

}
</style>

{% block script %}
<script>
$(document).ready(function(){
  loadTweetContainer("tweet-container")
});
</script>
{% endblock script %}



{% block content %}

   
    <div class='row'>
        <div class='col-sm-12'>
               {% if request.GET.q %}
                <p class='lead'>Results for {{ request.GET.q }}</p>
                <hr/>
               {% endif %}
        </div>
        <div class='col-sm-9 '>
          <h1>Tweets</h1>
          <hr/>

          <div id='tweet-container' data-url='/api/search/'>
            
          </div>
          <a href='#' id='loadmore'>Load More Tweets</a>


        </div>
        <div class='col-sm-3'>
          <h1>Users</h1>
           <hr/>
          {% for user in users %}
            <a href='/{{ user.username}}/'>{{ user.username}}</a><br/>

          {% empty %}
          <p>No users found</p>
          {% endfor %}
        </div>
    </div>

{% endblock content %}

polc/templates/search_form.html
{% load static %}

{% block script %}

<script src="{% static 'js/custom.js' %}"></script>

{% endblock script %}


<div class='container'>
	 <form id ='main-search-form' method='GET' action='{% url "candidatesapp:candidatelist" %}'>
	      <div class="form-row">
	            <div class="col-12 col-md-9 mb-2 mb-md-0">
	                  <input class="form-control form-control-lg" id ="form_searchID" type='text' name='q' placeholder='Search for Politicians..' value='{{ request.GET.q }}'/>
	            </div>
	            <div class="col-12 col-md-3">
	                  <button  type="submit" class="btn btn-block btn-lg btn-primary">Search</button>
	            </div>
	      </div>
	</form>
</div>